spring:
  application:
    name: ms-customer
  h2:
    console:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
