spring:
  application:
    name: '{cipher}9d584c68d0898933d651ea59188c092ffc12c64a2502bd117b4453eab0cfc31b'
  h2:
    console:
      enabled: true
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}

server:
  port: ${SERVER_PORT:6945}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
