spring:
  application:
    name: '{cipher}f49029b9b6b53406618c8f1bc4fa6422b49eb87488d122e2648e46b4577c3dc4'

server:
  port: ${SERVER_PORT:8762}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
