spring:
  application:
    name: ms-discovery

server:
  port: ${SERVER_PORT:8762}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
