server:
  port: ${SERVER_PORT:8181}
spring:
  application:
    name: '{cipher}594741ad7499193eb6175f571f92e28d7a374d2e9ecc4fe238c6029e627803c4'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
