spring:
  application:
    name: ms-product
  h2:
    console:
      enabled: true
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}

server:
  port: ${SERVER_PORT:7878}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
