spring:
  application:
    name: '{cipher}163b2bacceaf27251835274f1e1a066b6bfa0f009ff1153a2ba40f70e5fe4ba9'
  h2:
    console:
      enabled: true
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}

server:
  port: ${SERVER_PORT:8743}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
